version: '3.7'

services:
  xero_api:
    image: jaypeng2015/show-me-the-money
    ports:
      - '3000:3000'
  smtm_client:
    build:
      dockerfile: ./client/Dockerfile
      context: .
    container_name: smtm_client
    depends_on:
      - smtm_server
      - xero_api
    working_dir: /app/client
    volumes:
      - ./client:/app/client
  smtm_server:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    container_name: smtm_server
    working_dir: /app/server
    volumes:
      - ./server:/app/server
